FoodieStore/FoodieStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FoodieStore.Models;
using FoodieStore.Repositories;

namespace FoodieStore.Controllers
{
    
    public class HomeController : Controller
    {
        ProductsRepository productsRepository = new ProductsRepository();
        OrdersRepository ordersRepos = new OrdersRepository();

        [Authorize]
        public ActionResult CustOrders(string name)
        {
            List<OrdersJoin> customerOrders = new List<OrdersJoin>();
            using (App_Context db = new App_Context())
            {
                int userId = db.Users.Where(n => n.Username == name).Select(i => i.UserId).FirstOrDefault();
                //customerOrders = db.Orders.Where(c => c.UserId == userId).OrderByDescending(c => c.OrderDate).ToList();
                customerOrders = (from ord in db.Orders
                                  join ordDet in db.OrderDetails on ord.OrderId equals ordDet.OrderId
                                  join prod in db.Products on ordDet.ProductId equals prod.ProductId
                                  where ord.Username == name
                                  select new OrdersJoin
                                  {
                                      State = ord.OrderState,
                                      OrderDate = ord.OrderDate,
                                      Quantity = ordDet.Quantity,
                                      ProductPrice = ordDet.ProductPrice,
                                      ProductName = prod.ProductName
                                  }).ToList();

                Session["CustomDet"] = userId;

                //if (name != db.Users.)
            }



            return View(customerOrders);
        }

        [Authorize]
        public ActionResult EditAccount(string name)
        {
            User user;
            using (var db = new App_Context())
            {
                user = db.Users.Where(i => i.Username == name).SingleOrDefault();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAccountSubmit(User user)
        {
            if (!ModelState.IsValid)
            {
                return View("EditAccount",user);
            }
            User _user = new User();
            using(var db = new App_Context())
            {
                _user = db.Users.SingleOrDefault(i => i.Username == user.Username);
                if (_user!=null)
                {
                    _user.Username = user.Username;
                    _user.Password = user.Password;
                    _user.Salt = user.Salt;
                    _user.Email = user.Email;
                    _user.City = user.City;
                    _user.Firstname = user.Firstname;
                    _user.Lastname = user.Lastname;
                    _user.Phone = user.Phone;
                    _user.RoleId = user.RoleId;
                    _user.Address = user.Address;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index","Home");
        }

        List<Product> product = new List<Product>();
        // GET: Home
        public ActionResult Index()
        {
            return View(productsRepository.GetAllDishes());
        }

        public ActionResult DailyDishes()
        {
            Random r = new Random();
            List<Product> allDishes;
            using (var db = new App_Context())
            {
                allDishes = db.Products.Where(i => i.Category.CategoryId == 2).Take(3).ToList();

            }

            return View(allDishes);
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Menu()
        {
            
            return View(productsRepository.GetAllProducts());
        }

        public ActionResult ProductByCat(int id)
        {

            using (var db = new App_Context())
            {
                var allProducts = db.Products.Where(i => i.Category.CategoryId == id).ToList();
                product = allProducts;
            }
            return View(product);
        }
    }
}

FoodieStore/FoodieStore/Controllers/PdfController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using FoodieStore.Models;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using System.Text;

namespace FoodieStore.Controllers
{
    public class PdfController : Controller
    {
        private App_Context db = new App_Context();


        //public ActionResult ExportToPdf_Click(object sender, EventArgs e, int id)
        //{
        //    //var UserId = (string)Session["UserName"];
        //    string File = "PDFUserDetails";
        //    List<OrdersJoin> result = (from ord in db.Orders
        //                               join ordDet in db.OrderDetails on ord.OrderId equals ordDet.OrderId
        //                               join prod in db.Products on ordDet.ProductId equals prod.ProductId
        //                               where ord.Username == User.Identity.Name
        //                               select new OrdersJoin
        //                               {
        //                                   State = ord.OrderState,
        //                                   OrderDate = ord.OrderDate,
        //                                   Quantity = ordDet.Quantity,
        //                                   ProductPrice = ordDet.ProductPrice,
        //                                   ProductName = prod.ProductName
        //                               }).ToList();
        //    ExportListToPDF(result, File);

        //    return View("CustOrders", "Home");
        //}

        public ActionResult ExportToExcel()
        {
            var data = (from ord in db.Orders
                        join ordDet in db.OrderDetails on ord.OrderId equals ordDet.OrderId
                        join prod in db.Products on ordDet.ProductId equals prod.ProductId
                        where ord.Username == User.Identity.Name
                        select new OrdersJoin
                        {
                            State = ord.OrderState,
                            OrderDate = ord.OrderDate,
                            Quantity = ordDet.Quantity,
                            ProductPrice = ordDet.ProductPrice,
                            ProductName = prod.ProductName
                        }).ToList();

            GridView view = new GridView();
            view.DataSource = data;
            view.DataBind();

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=myorders.xls");
            Response.ContentType = "application/ms-excel";
            Response.ContentEncoding = Encoding.Unicode;
            Response.BinaryWrite(Encoding.Unicode.GetPreamble());
            Response.Charset = "";
            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter htw = new HtmlTextWriter(sw))
                {
                    view.RenderControl(htw);
                    Response.Output.Write(sw.ToString());
                    Response.Flush();
                    Response.End();
                }
            }

            return View();
        }

        //private void ExportListToPDF(List<OrdersJoin> result, string File)
        //{
        //    Response.ContentType = "application/pdf";
        //    Response.AddHeader("content-disposition", "attachment;filename=UserDetails.pdf");
        //    Response.Cache.SetCacheability(HttpCacheability.NoCache);
        //    StringWriter sw = new StringWriter();//Edw exei thn HTML tou table
        //    HtmlTextWriter hw = new HtmlTextWriter(sw);
        //    GridView gridView = new GridView();
        //    gridView.DataSource = result;
        //    gridView.DataBind();
        //    gridView.RenderControl(hw);
        //    StringReader sr = new StringReader(sw.ToString());
        //    Document pdfDoc = new Document(PageSize.A4, 50f, 50f, 50f, 50f);
        //    HTMLWorker htmlparser = new HTMLWorker(pdfDoc);
        //    //FontFactory.Register(Path.Combine(_webHelper.))
        //    PdfWriter writer = PdfWriter.GetInstance(pdfDoc, Response.OutputStream);
        //    pdfDoc.Open();
        //    XMLWorkerHelper worker = XMLWorkerHelper.GetInstance();
        //    //worker.ParseXHtml(writer,pdfDoc,Cha,)
        //    htmlparser.Parse(sr);
        //    pdfDoc.Close();
        //    Response.Write(pdfDoc);
        //    Response.End();
        //    gridView.AutoGenerateColumns = true;
        //}
    }
}

FoodieStore/FoodieStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ***** Breadcumb Area Start ***** -->
<div class="breadcumb-area bg-img bg-overlay" style="background-image: url(/Contents/img/bg-img/hero-4.jpg)">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="breadcumb-content">
                    <h2>Επικοινωνία</h2>
                    <p><i class="fa fa-phone" aria-hidden="true"></i> <a href="tel:210000000">210000000</a></p>
                    <p><i class="fa fa-map-marker" aria-hidden="true"></i>Αθήνα</p>
                    <p><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:someone@yoursite.com">lorem.ipsum@dolor.com</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Breadcumb Area End ***** -->
<!-- ***** Contact Area Start ***** -->
<div class="caviar-contact-area d-md-flex align-items-center" id="contact">
    <div class="contact-form-area d-flex justify-content-end">
        <div class="contact-form">
            <div class="contact-form-title">
                <p>get in touch</p>
            </div>
            <form action="#">
                <div class="row">
                    <div class="col-12">
                        <input type="text" class="form-control" placeholder="Your Name">
                    </div>
                    <div class="col-12">
                        <input type="email" class="form-control" placeholder="Your Email">
                    </div>
                    <div class="col-12">
                        <textarea name="message" class="form-control" id="Message" cols="30" rows="10" placeholder="Your Message"></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn caviar-btn"><span></span> Send Message</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="caviar-map-area wow fadeInRightBig" data-wow-delay="0.5s">
        <div id="googleMap"></div>
    </div>
</div>
<!-- ***** Contact Area End ***** -->
@Html.Partial("_ModalPartial")

FoodieStore/FoodieStore/Views/Home/CustOrders.cshtml
@model IEnumerable<FoodieStore.Models.OrdersJoin>

@{
    ViewBag.Title = "CustOrders";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var UserId = (string)Session["UserName"];
}


<div class="container orders-page">
    <span>
        <a href="@Url.Action("ExportToExcel","Pdf")?name=@UserId" title="Download to Xls format">
            <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i>
        </a>
    </span>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.State)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductName)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                </tr>
            }

        </table>
</div>

FoodieStore/FoodieStore/Views/Home/DailyDishes.cshtml
@model IEnumerable<FoodieStore.Models.Product>
@{
    Layout = null;
}
@foreach (var item in Model)
{
    <div class="caviar-single-dish wow fadeInUp" data-wow-delay="0.5s">
        <img class="cat-img" src="@item.ImagePath" alt="@item.Description">
        <div class="dish-info">
            <h6 class="dish-name">@item.ProductName</h6>
            <p class="dish-price">@item.ProductPrice</p>
        </div>
        <div class="button-container">
            <a class="AddLink buy-button" href="#" data-id="@item.ProductId" title="Add to Cart">Αγορά</a>
        </div>
    </div>
}

    <script type="text/javascript">
    $(function () {
            $(".AddLink").click(function () {
                var recordToAdd = $(this).attr("data-id");
                if (recordToAdd != '') {
                    $.post("/ShoppingCart/AddToCart", {
                        "id": recordToAdd
                    },
                        function (data) {
                            $('#cart-status').text(data.CartCount);
                        });
                }
            });
        });</script>

FoodieStore/FoodieStore/Views/Home/EditAccount.cshtml
@model FoodieStore.Models.User

@{
    ViewBag.Title = "EditAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="caviar-about-us-area section-padding-150 register-page" id="about">

    <div id="account-main" class="col-md-12">
        <fieldset>
            <legend style="max-width:300px;">Επεξεργασία Λογαριασμού</legend>
            @using (Html.BeginForm("EditAccountSubmit", "Home"))

            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.UserId)

                <div class="row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "input-focus form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "input-focus form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.RoleId, new { htmlAttributes = new { @class = "input-focus form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "input-focus form-control" } })
                            @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "input-focus form-control" } })
                            @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input-focus form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "input-focus form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "input-focus form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "input-focus form-control" } })
                            @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-3">
                    <div class="col-md-10">
                        @Html.HiddenFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-3">
                    <div class="col-md-10">
                        @Html.HiddenFor(model => model.Salt, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Salt, "", new { @class = "text-danger" })
                    </div>
                </div>
                <button type="submit" class="btn btn-danger">Αποθήκευση Αλλαγών</button>
            </div>
            }
        </fieldset>
    </div>
</section>

FoodieStore/FoodieStore/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Foodie-Delivery Service";
}


<section class="caviar-hero-area" id="home">
    <!-- Welcome Social Info -->
    <div class="welcome-social-info">
        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    </div>
    <!-- Welcome Slides -->
    <div class="caviar-hero-slides owl-carousel">
        <!-- Single Slides -->
        <div class="single-hero-slides bg-img" style="background-image: url(/Contents/img/bg-img/hero-1.jpg);">
            <div class="container h-100">
                <div class="row h-100 align-items-center">
                    <div class="col-11 col-md-6 col-lg-4">
                        <div class="hero-content">
                            <h2>Πείνασες; Ώρα να παραγγείλεις!</h2>
                            <p>Μοναδικές Γαστρονομικές επιλογές καθημερινά στο σπίτι και στο γραφείο σου.</p>
                            <a href="@Url.Action("Menu","Home")" class="btn caviar-btn"><span></span> Δες το Μενού</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Slider Nav -->
            <div class="hero-slides-nav bg-img" style="background-image: url(/Contents/img/bg-img/hero-2.jpg);"></div>
        </div>
        <!-- Single Slides -->
        <div class="single-hero-slides bg-img" style="background-image: url(/Contents/img/bg-img/hero-2.jpg);">
            <!-- Slider Nav -->
            <div class="hero-slides-nav bg-img" style="background-image: url(/Contents/img/bg-img/hero-1.jpg);"></div>
        </div>
    </div>
</section>

<!-- ****** About Us Area Start ****** -->
<section class="caviar-about-us-area section-padding-150" id="about">
    <div class="container">
        <!-- About Us Single Area -->
        <div class="row align-items-center">
            <div class="col-12 col-md-6">
                <div class="about-us-thumbnail wow fadeInUp" data-wow-delay="0.5s">
                    <img src="~/Contents/img/bg-img/about-1.jpg" alt="flowers">
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-5 ml-md-auto">
                <div class="section-heading">
                    <h2>About Us</h2>
                </div>
                <div class="about-us-content">
                    <span>restaurant style</span>
                    <p>
                       Απο τον Απρίλιο του 2018 μας βρίσκεται στην περιοχή του Ψυρρή, με μια μεγάλη ποικιλία απο πιάτα της ώρας
                        και διάφορα ορεκτικά.
                    </p>
                </div>
            </div>
        </div>
        <!-- About Us Single Area -->
        <div class="about-us-second-part">
            <div class="row align-items-center pt-200">
                <div class="col-12 col-md-6 col-lg-5">
                    <div class="about-us-content">
                        <span>our chef</span>
                        <p>
                            Όταν η γνώση, η εμπειρία και το πάθος συναντούν τους έμπειρους chefs μας, 
                            το αποτέλεσμα δε μπορεί παρά να είναι ένα γευστικά τέλειο πιάτο. 
                            Χρησιμοποιώντας πάντα φρέσκα, αγνά και ποιοτικά υλικά, 
                            φροντίζουμε να απολαμβάνεις τις κλασικές συνταγές της μαμάς , 
                            αλλά και συνταγές με άρωμα ανανέωσης που καλύπτουν και τον πιο απαιτητικό ουρανίσκο.
                        </p>
                    </div>
                </div>
                <div class="col-12 col-md-6 ml-md-auto">
                    <div class="about-us-thumbnail wow fadeInUp" data-wow-delay="0.5s">
                        <img src="~/Contents/img/bg-img/about-2.jpg" alt="sef_image">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ****** About Us Area End ****** -->
<!-- ****** Dish Menu Area Start ****** -->
<section class="caviar-dish-menu" id="menu">
    <div class="container">
        <div class="row">
            <div class="col-12 menu-heading">
                <div class="section-heading text-center">
                    <h2>Προτάσεις Ημέρας</h2>
                </div>
                <!-- btn -->
                <a href="@Url.Action("Menu","Home")" class="btn caviar-btn"><span></span> Δες το Μενού</a>
            </div>
        </div>
        <div class="row">
            @RenderPage("DailyDishes.cshtml")
        </div>
    </div>
</section>
<!-- ****** Dish Menu Area End ****** -->
<!-- Modal -->
@Html.Partial("_ModalPartial")

FoodieStore/FoodieStore/Views/Home/Menu.cshtml
@model IEnumerable<FoodieStore.Models.Product>
@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*Διέγραψα το Special content*@
<!-- ***** Breadcumb Area Start ***** -->
<div class="breadcumb-area bg-img bg-overlay" style="background-image: url(/Contents/img/bg-img/hero-2.jpg)">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="breadcumb-content">
                    <h2>Μενού</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Breadcumb Area End ***** -->
<!-- ***** Menu Area Start ***** -->
<div class="caviar-food-menu section-padding-150 clearfix">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <div class="food-menu-title">
                    <h2>Μενού</h2>
                </div>
            </div>

            <div class="col-10">
                <div class="caviar-menu-slides owl-carousel clearfix">

                    <div class="caviar-portfolio clearfix">
                        <!-- Single Gallery Item -->
                        <div class="single_menu_item breakfast wow fadeInUp">
                            @foreach (var item in Model)
                            {
                                <div class="d-sm-flex align-items-center">

                                    <div class="dish-thumb">
                                        <img class="rounded menu-img" src="@item.ImagePath" alt="@item.Description">
                                    </div>
                                    <div class="dish-description">
                                        <h3>@item.ProductName</h3>
                                        <p>@item.Description</p>
                                    </div>
                                    <div class="dish-value">
                                        <h3>@item.ProductPrice</h3>
                                    </div>
                                    <div class="button-container">
                                        <a class="AddLink buy-button-menu" href="#" data-id="@item.ProductId" title="Add to Cart">+</a>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Menu Area End ***** -->
@Html.Partial("_ModalPartial")

FoodieStore/FoodieStore/Views/Home/ProductByCat.cshtml
@model IEnumerable<FoodieStore.Models.Product>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="caviar-dish-menu clearfix" id="menu">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-12 col-sm-6 col-md-4 mb-3" id="drinks-container">
                    <div class="caviar-single-dish wow fadeInUp" data-wow-delay="0.5s">
                        <img class="cat-img" src="@item.ImagePath" alt="@item.Description">
                        <div class="dish-info">
                            <h6 class="dish-name">@item.ProductName</h6>
                            <p class="dish-price">@item.ProductPrice</p>
                        </div>
                        <div class="button-container">
                            <a class="AddLink buy-button" data-id="@item.ProductId" title="Add to Cart">Αγορά</a>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</section>
@Html.Partial("_ModalPartial")