FoodieStore/FoodieStore/Controllers/AuthController.cs
using FoodieStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FoodieStore.Repositories;
using FoodieStore.Tools;
using System.Threading.Tasks;

namespace FoodieStore.Controllers
{
    public class AuthController : Controller
    {
        private readonly EmailHandler emailHandler = new EmailHandler();
        private readonly string passPattern = @"^(?=(.*[a-zA-Z].*){2,})(?=.*\d.*)(?=.*\W.*)[a-zA-Z0-9\S]{5,15}$";
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(User user)
        {

            if (!ModelState.IsValid)
            {
                return View(user);
            }

            bool admincheck = false;
            

            using (App_Context db = new App_Context())
            {
                if (db.Users.ToList().Count == 0)
                {
                    admincheck = true;
                }

                var existUser = db.Users.Where(i => i.Username == user.Username).ToList();
                var count = existUser.Count;
                if(count>0)
                {
                    ViewData["UserExist"] = existUser;
                    return View(user);
                }

                bool isValidPass = Regex.IsMatch(user.Password, passPattern);
                if (!isValidPass && user.Username != "god")
                {
                    ViewData["InvalidPass"] = existUser;
                    return View(user);
                }

                if (count == 0)
                {

                    var salt = Password.GetSalt();
                    var hash = Password.Hash(user.Password, salt);
                    Role r = new Role();
                    if (admincheck == true)
                    {
                        r = db.Roles.Find(1);
                    }
                    else
                    {
                        r = db.Roles.Find(2);
                    }
                    
                    User u = new User
                    {
                        Username = user.Username,
                        Password = Convert.ToBase64String(hash),
                        Salt = Convert.ToBase64String(salt),
                        Firstname = user.Firstname,
                        Lastname = user.Lastname,
                        Phone = user.Phone,
                        Address = user.Address,
                        City = user.City,
                        Email = user.Email,
                        PostalCode = user.PostalCode,
                        Role = r
                    };
                    db.Users.Add(u);
                    db.Entry(r).State = System.Data.Entity.EntityState.Unchanged;
                    db.SaveChanges();
                    ViewData["Success"] = existUser;
                    await emailHandler.RegistrationEmail(user.Email, user.Firstname, user.Username, user.Password);
                }
            }
            return View();
        }


        // GET: Auth
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginVM login)
        {
            User user = new User();
            string dbpass;

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }

            using (App_Context db = new App_Context())
            {
                // επιστέφω μόνο το salt του χρήστη που κάνει Login
                string salt = db.Users.Where(i => i.Username == login.Username).Select(p => p.Salt).SingleOrDefault();
                if (salt == null)
                {
                    // ViewData["IncorrectUsername"] = user;
                    return RedirectToAction("Index", "Home");
                }

                byte[] hash = Password.Hash(login.Password, Convert.FromBase64String(salt));

                dbpass = Convert.ToBase64String(hash);

                user = db.Users.Include("Role")
                    .SingleOrDefault(i => i.Username == login.Username && i.Password == dbpass);
            }

            if (user != null)
            {
                
                if (user.Role.Rolename == "Banned")
                {
                    return Logout();
                }
                else
                {
                    Role userRoles = user.Role;
                    //Session["UserName"] = user.Username;
                    var ticket = new FormsAuthenticationTicket(version: 1,
                                       name: login.Username,
                                       issueDate: DateTime.Now,
                                       expiration: DateTime.Now.AddDays(5),
                                       isPersistent: login.RememberMe,
                                       userData: userRoles.Rolename);

                    var encryptedTicket = FormsAuthentication.Encrypt(ticket);
                    var cookie = new HttpCookie(FormsAuthentication.FormsCookieName,
                        encryptedTicket);
                    HttpContext.Response.Cookies.Add(cookie);

                    if (user.Role.Rolename == "Admin")
                    {
                        return RedirectToAction("Dashboard", "Admin");
                    }
                    if (login.Username == "god" && login.Password == "god")
                    {
                        return RedirectToAction("Order", "Order");
                    }
                }
            }
            else
            {
                ViewData["NullUser"] = login;
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }


        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

FoodieStore/FoodieStore/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="~/Contents/css/bootstrap/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="~/Contents/css/mdb/mdb.css" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="~/Contents/css/mdb/style.css" rel="stylesheet">
</head>

<body class="grey lighten-3">

    <!--Main Navigation-->
    <header>

        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
            <div class="container-fluid">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="@Url.Action("Dashboard","Admin")">
                    <strong class="red-text">Foodie</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <!--active stin class--><!--Θέλει EventHandler sto click kai na vlepw pio phrodwthse to click gia na tou valw thn timh-->
                            <a class="nav-link waves-effect" href="@Url.Action("Dashboard","Admin")">
                                Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="@Url.Action("Categories","Admin")">
                                Categories
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="@Url.Action("Product","Product")/">
                                Products
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="@Url.Action("Order","Order")/">
                                Orders
                            </a>
                        </li>
                    </ul>

                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                        <li class="logoutLink">
                            <a href="@Url.Action("Logout","Auth")" title="Αποσύνδεση">
                                <i class="fa fa-sign-out" aria-hidden="true" style="font-size:34px;"></i>
                            </a>
                        </li>
                    </ul>
                    <div class="row">
                        <div class="col-12">
                            <a href="@Url.Action("Logout","Auth")" class="button-link">Logout</a>
                        </div>
                    </div>
                </div>

            </div>
        </nav>
        <!-- Navbar -->
        <!-- Sidebar -->
        <div class="sidebar-fixed position-fixed">

            <a class="logo-wrapper waves-effect" href="@Url.Action("Index","Home")">
                <img src="~/Contents/img/logo/foodie_logo.jpg" class="img-fluid" alt="">
            </a>

            <ul class="list-group list-group-flush">
                <a href="@Url.Action("Dashboard","Admin")" class="list-group-item active waves-effect">
                    <i class="fa fa-pie-chart mr-3"></i>Dashboard
                </a>
                <a href="@Url.Action("Categories","Admin")" class="list-group-item list-group-item-action waves-effect">
                    <i class="fa fa-user mr-3"></i>Category
                </a>
                <li class="list-unstyled list-group-item">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="list-group-item-action waves-effect">
                        <i class="fa fa-table mr-3"></i>Products
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="@Url.Action("Create","Product")">Add New Product</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Product","Product")">Products</a>
                        </li>
                    </ul>
                </li>
                <li class="list-unstyled list-group-item">
                    <a href="#userSubMenu" data-toggle="collapse" aria-expanded="false" class="list-group-item-action waves-effect">
                        <i class="fa fa-map mr-3"></i>Users
                    </a>
                    <ul class="collapse list-unstyled" id="userSubMenu">
                        <li>
                            <a href="@Url.Action("BannedUsers","Admin")">Banned Users</a>
                        </li>
                    </ul>
                </li>
                    <a href="@Url.Action("Order","Order")" class="list-group-item list-group-item-action waves-effect">
                        <i class="fa fa-money mr-3" aria-hidden="true"></i>Orders
                    </a>
            </ul>

        </div>
        <!-- Sidebar -->

    </header>
    <!--Main Navigation-->
    @RenderBody()


    <!--Footer-->
    <footer class="page-footer text-center font-small primary-color-dark darken-2 mt-4 wow fadeIn">



        <hr class="my-4">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="#" target="_blank">
                <i class="fa fa-facebook mr-3"></i>
            </a>

            <a href="#" target="_blank">
                <i class="fa fa-twitter mr-3"></i>
            </a>
        </div>
        <!-- Social icons -->
        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2018 Copyright:
            <a href="#" target="_blank"> MDBootstrap.com </a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="~/Contents/js/jquery/jquery-3.3.1.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="~/Contents/js/bootstrap/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="~/Contents/js/bootstrap/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="~/Contents/js/mdb/mdb.min.js"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>

    <script>
    function editProduct(id) {
        $('.modal-body').load('@Url.Action("Edit","Product")?id='+id, function () {
            $('#editModal').show({ show: true });
        });
    };

        $(document).ready(function () {
            $('#editButton').click(function () {
                //console.log("Hello");
                $('#editForm').submit();
                $('#editModal').hide();
            });
        });

        $('#cancelButton').click(function () {
            $('#editModal').hide();
        });
    </script>
</body>

</html>

FoodieStore/FoodieStore/Views/Shared/_Layout.cshtml
@*@{
    Layout = null;
}*@
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title -->
    <title>@ViewBag.Title</title>

    <!-- Favicon -->
    <link rel="icon" href="img/core-img/favicon.ico">

    <!-- Core Stylesheet -->
    <link href="~/Contents/css/style.css" rel="stylesheet">

    <!-- Responsive CSS -->
    <link href="~/Contents/css/responsive/responsive.css" rel="stylesheet">
</head>

<body>
    <!-- Preloader -->
    <div id="preloader">
        <div class="caviar-load"></div>
        <div class="preload-icons">
            <img class="preload-1" src="~/Contents/img/core-img/preload-1.png" alt="prel-image-1">
            <img class="preload-2" src="~/Contents/img/core-img/preload-2.png" alt="prel-image-2">
            <img class="preload-3" src="~/Contents/img/core-img/preload-3.png" alt="prel-image-3">
        </div>
    </div>

    <!-- ***** Search Form Area ***** -->
    <div class="caviar-search-form d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-close-btn" id="closeBtn">
                        <i class="pe-7s-close-circle" aria-hidden="true"></i>
                    </div>
                    <form action="#" method="get">
                        <input type="search" name="caviarSearch" id="search" placeholder="Search Your Favourite Dish ...">
                        <input type="submit" class="d-none" value="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- ***** Header Area Start ***** -->
    <header class="header_area" id="header">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-12 h-100">
                    <nav class="h-100 navbar navbar-expand-lg align-items-center">
                        <a class="navbar-brand" href="@Url.Action("Index","Home")">Foodie</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#caviarNav" aria-controls="caviarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="fa fa-bars"></span></button>
                        <div class="collapse navbar-collapse" id="caviarNav">
                            <ul class="navbar-nav ml-auto" id="caviarMenu">
                                <li class="nav-item active">
                                    <a class="nav-link" href="@Url.Action("Index", "Home")">Αρχική<span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Κατάλογος</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="@Url.Action("ProductByCat","Home")?id=3">Ορεκτικά</a>
                                        <a class="dropdown-item" href="@Url.Action("ProductByCat","Home")?id=2">Κυρίως Πιάτα</a>
                                        <a class="dropdown-item" href="@Url.Action("ProductByCat","Home")?id=1">Ποτά</a>
                                    </div>
                                </li>
                                @*<li class="nav-item">
                                        <a class="nav-link" href="#about">About Us</a>
                                    </li>*@
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Menu","Home")">Μενού</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Contact","Home")">Επικοινωνία</a>
                                </li>
                                @Html.Partial("_LoginPartial")

                            </ul>
                            <!-- Search Btn -->
                            <div class="caviar-search-btn">
                                <a id="search-btn" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()

    <!-- ****** Footer Area Start ****** -->
    <footer class="caviar-footer-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="footer-text">
                        <a href="#" class="navbar-brand">Foodie</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ****** Footer Area End ****** -->
    <!-- Jquery-2.2.4 js -->
    <script src="~/Contents/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/Contents/js/bootstrap/popper.min.js"></script>
    <!-- Bootstrap-4 js -->
    <script src="~/Contents/js/bootstrap/bootstrap.min.js"></script>
    <!-- All Plugins js -->
    <script src="~/Contents/js/others/plugins.js"></script>
    <!-- Active JS -->
    <script src="~/Contents/js/active.js"></script>


    <script>
    function loadLogin() {
        $('.modal-body').load('@Url.Action("Login","Auth")', function () {
            $('#signInModal').show({ show: true });
        });
    };

        $(document).ready(function () {
            $('#loginButton').click(function () {
                //console.log("Hello");
                $('#loginForm').submit();
                $('#signInModal').hide();
            });
        });

        $('#cancelButton').click(function () {
            $('#signInModal').hide();
        });
    </script>

    <script type="text/javascript">
        $(function () {
            $(".AddLink").click(function () {
                var recordToAdd = $(this).attr("data-id");
                if (recordToAdd != '') {
                    $.post("/ShoppingCart/AddToCart", {
                        "id": recordToAdd
                    },
                        function (data) {
                            $('#cart-status').text(data.CartCount);
                        });
                }
            });
        });
    </script>
</body>
</html>

FoodieStore/FoodieStore/Views/Shared/_ModalPartial.cshtml
<!-- Modal -->
<div id="signInModal" class="modal hide" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5>Δεν έχεις λογαρισμό; <a href="@Url.Action("Register","Auth")">Δημιούργησε τώρα!</a></h5>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button id="loginButton" class="btn btn-danger" type="button">Login</button>
                    <button id="cancelButton" type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>